language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rspec
cache: bundler
before_script:
  # - bundle install
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 339a795b0e3010b4361e3739e3abd36ce628e3c0545615b67c47bfbe8240d929
notifications:
  email:
    recipients:
      - wanghaotian@robodou.cn
    on_success: always
    on_failure: always
